@accessibility @a11y @wcag
Feature: As Scheduler, I want to receive notifications for recurring conflicts to proactively manage scheduling - Accessibility Tests
  As a user
  I want to test accessibility tests
  So that I can ensure quality and reliability

  Background:
    Given the system is ready for testing
    And the test environment is properly configured

  @high @tc-acce-001
  Scenario: TC-ACCE-001 - Verify complete keyboard navigation for recurring conflict notifications
    Given user is logged in as Scheduler
    And at least one recurring conflict notification is present in the notification panel
    And user is on the Scheduling Dashboard page
    And screen reader is not active (testing keyboard-only navigation)
    When press Tab key repeatedly from the top of the page until focus reaches the notification bell icon
    Then notification bell icon receives visible focus indicator (2px solid blue outline), focus order is logical following visual layout
    And press Enter key or Space bar while notification bell has focus
    Then notification panel opens, focus automatically moves to first notification item in the panel, panel has role='dialog' and aria-label='Notifications'
    And press Tab key to navigate through notification items and action buttons
    Then focus moves sequentially through: notification title, 'View Details' button, 'Resolve Conflict' button, 'View Alternatives' button, 'Dismiss' button, each element shows visible focus indicator
    And press Escape key while focus is within the notification panel
    Then notification panel closes, focus returns to notification bell icon, panel closure is announced to assistive technologies
    And navigate to notification preferences page using Tab key, locate 'Save Preferences' button, and press Enter
    Then all form controls (checkboxes, dropdowns) are keyboard accessible, preferences are saved, success message receives focus and is announced
    And all interactive elements are keyboard accessible without mouse
    And focus order is logical and follows visual layout
    And focus indicators are visible on all interactive elements
    And no keyboard traps exist in notification interface

  @high @tc-acce-002
  Scenario: TC-ACCE-002 - Verify screen reader announces recurring conflict notifications with complete context
    Given user is logged in as Scheduler
    And nVDA or JAWS screen reader is active and running
    And a new recurring conflict notification has just been generated
    And user is on the Scheduling Dashboard page
    When wait for recurring conflict notification to be generated by the system
    Then screen reader announces via ARIA live region: 'Alert: New recurring conflict notification. Conference Room A conflict has occurred 4 times. Press Alt+N to view details.' with assertive politeness level
    And navigate to notification bell icon using screen reader navigation commands
    Then screen reader announces: 'Notifications button, 1 unread notification, collapsed' with proper role and state information
    And activate notification bell icon using Enter key
    Then screen reader announces: 'Notifications dialog opened, 1 notification. Recurring Conflict: Conference Room A - Team Meeting, occurred 4 times in last 30 days, link, button View Details, button Resolve Conflict'
    And navigate through notification details using arrow keys
    Then screen reader reads all notification content including: conflict type, resources involved, frequency data, last occurrence date, and available actions with proper semantic structure (headings, lists, buttons)
    And navigate to 'View Alternatives' button and activate it
    Then screen reader announces: 'Alternatives dialog opened, 3 alternative time slots available, list with 3 items' and reads each alternative with proper context
    And all notification content is accessible to screen reader users
    And aRIA live regions announce dynamic content changes
    And semantic HTML and ARIA labels provide complete context
    And screen reader users can understand and act on notifications independently

  @high @tc-acce-003
  Scenario: TC-ACCE-003 - Verify color contrast ratios meet WCAG 2.1 AA standards for notification elements
    Given user is logged in as Scheduler
    And recurring conflict notification is visible in notification panel
    And color contrast analyzer tool is available (e.g., browser extension or WAVE tool)
    And application is displayed at 100% zoom level
    When use color contrast analyzer to measure contrast ratio between notification title text and background
    Then contrast ratio is at least 4.5:1 for normal text (e.g., black text #000000 on white background #FFFFFF = 21:1, passes WCAG AA)
    And measure contrast ratio for notification badge indicator (red badge showing unread count)
    Then badge background color has contrast ratio of at least 3:1 against adjacent colors, white text on red badge has ratio of at least 4.5:1
    And check contrast for action buttons ('Resolve Conflict', 'View Alternatives') in normal state
    Then button text has contrast ratio of at least 4.5:1 against button background, button border has contrast of at least 3:1 against page background
    And check contrast for action buttons in hover and focus states
    Then hover and focus states maintain minimum 4.5:1 contrast ratio for text, focus indicator has at least 3:1 contrast against background
    And verify color is not the only means of conveying information (e.g., recurring conflict severity)
    Then high-priority conflicts use both red color AND icon (exclamation mark) or text label ('High Priority'), information is not conveyed by color alone
    And all text meets WCAG 2.1 AA contrast requirements (4.5:1 for normal text, 3:1 for large text)
    And uI components and graphical objects meet 3:1 contrast requirement
    And color is not the sole means of conveying information
    And interface is usable for users with color vision deficiencies

  @medium @tc-acce-004
  Scenario: TC-ACCE-004 - Verify notification interface remains functional and readable at 200% zoom level
    Given user is logged in as Scheduler
    And browser is set to 100% zoom level initially
    And recurring conflict notification is present in notification panel
    And browser window is at standard desktop resolution (1920x1080)
    When increase browser zoom level to 200% using Ctrl + Plus key (or Cmd + Plus on Mac)
    Then page content scales proportionally, notification bell icon remains visible and accessible in viewport
    And click notification bell icon to open notification panel at 200% zoom
    Then notification panel opens and fits within viewport without horizontal scrolling, content reflows appropriately, all text remains readable
    And verify all notification content is visible without requiring horizontal scroll
    Then notification title, description, frequency data, and action buttons are all visible, text wraps appropriately, no content is cut off or hidden
    And navigate to notification preferences page at 200% zoom
    Then form controls (checkboxes, dropdowns, buttons) remain functional and properly sized, labels are associated with controls, no overlapping elements
    And test all interactive elements (buttons, links, form controls) at 200% zoom
    Then all interactive elements remain clickable with adequate touch target size (minimum 44x44 pixels), no functionality is lost due to zoom level
    And interface remains fully functional at 200% zoom per WCAG 2.1 AA requirement
    And no horizontal scrolling is required to view content
    And all text is readable and all functionality is accessible
    And layout adapts responsively to increased zoom level

  @high @tc-acce-005
  Scenario: TC-ACCE-005 - Verify ARIA live regions announce dynamic notification updates appropriately
    Given user is logged in as Scheduler
    And screen reader (NVDA or JAWS) is active
    And user is on Scheduling Dashboard with notification panel closed
    And system is about to detect a new recurring conflict
    When trigger a recurring conflict while user is focused on a different part of the page
    Then aRIA live region with aria-live='assertive' announces: 'New recurring conflict detected. Conference Room A has conflicted 4 times.' without interrupting user's current task
    And open notification panel and mark a notification as read
    Then aRIA live region with aria-live='polite' announces: 'Notification marked as read' after user completes current action
    And click 'Resolve Conflict' button and wait for system to process resolution
    Then aRIA live region announces: 'Processing conflict resolution...' followed by 'Conflict resolved successfully. Schedule updated.' with appropriate timing
    And verify notification count badge updates when new notification arrives
    Then badge count updates visually AND aria-label updates from 'Notifications button, 1 unread' to 'Notifications button, 2 unread', screen reader announces update
    And test error scenario: attempt to resolve conflict when network is offline
    Then aRIA live region with aria-live='assertive' immediately announces: 'Error: Unable to resolve conflict. Network connection lost. Please try again.' with role='alert'
    And all dynamic content changes are announced to screen reader users
    And aRIA live regions use appropriate politeness levels (assertive for urgent, polite for non-urgent)
    And announcements provide complete context without being overly verbose
    And error messages are announced immediately with assertive politeness

  @high @tc-acce-006
  Scenario: TC-ACCE-006 - Verify focus management when opening and closing notification modals and dialogs
    Given user is logged in as Scheduler
    And recurring conflict notification is present
    And user is navigating using keyboard only
    And focus is currently on a button in the main content area
    When press Tab key until notification bell icon receives focus, then press Enter to open notification panel
    Then notification panel opens, focus automatically moves to first focusable element inside panel (close button or first notification), focus is trapped within panel (Tab cycles through panel elements only)
    And press Tab key repeatedly to cycle through all focusable elements in notification panel
    Then focus cycles through: close button, notification items, action buttons, and returns to close button, focus never escapes to background content
    And click 'View Alternatives' button to open alternatives modal
    Then alternatives modal opens, focus moves to modal's first focusable element (close button or first alternative option), notification panel remains open in background but is not focusable
    And press Escape key to close alternatives modal
    Then alternatives modal closes, focus returns to 'View Alternatives' button in notification panel (the element that triggered the modal)
    And press Escape key again to close notification panel
    Then notification panel closes, focus returns to notification bell icon (the element that opened the panel), user can continue keyboard navigation from that point
    And focus is properly managed when opening and closing dialogs
    And focus returns to triggering element when dialogs close
    And focus is trapped within modal dialogs (cannot Tab to background)
    And escape key closes dialogs and returns focus appropriately

